//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int Age { get; set; }
        public int ClassID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
    }
}
