//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlluringDecors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Contracts = new HashSet<Contract>();
            this.DesignPackages = new HashSet<DesignPackage>();
        }
    
        public int id { get; set; }
        public string ProjectName { get; set; }
        public int Area { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
        public string Address { get; set; }
        public int ImageID { get; set; }
        public string Status { get; set; }
        public int DesignTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesignPackage> DesignPackages { get; set; }
        public virtual DesignType DesignType { get; set; }
        public virtual Image Image { get; set; }
    }
}
